version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install packets
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: yarn run test
      - run:
          name: prepare for nyc
          command: sudo mkdir .nyc_output
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      - run:
          name: clean after nyc
          command: sudo rm -rf .nyc_output
